config/routes.rb
Rails.application.routes.draw do

  namespace :api do 
    namespace :v1 do 
      resources :flashcards
      resources :flashcard_sets
    end
  end

  devise_for :users
    get 'welcome/home'
    get '/app', to: 'welcome#app', as: 'app'
  
    root 'welcome#home'
    get '*path' => redirect('/')
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  belongs_to :flashcard_set 
  has_one_attached :image 
end

app/models/flashcard_set.rb
class FlashcardSet < ApplicationRecord
  has_many :flashcards 
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :flashcard_sets 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/flashcard_sets_controller.rb
require 'pry'
module Api 
  module V1
    class FlashcardSetsController < ApplicationController

      def new
      end 

      def create 
       binding.pry
        if user_signed_in?
          @flashcard_set = current_user.flashcard_sets.build(title: params[:title], description: params[:description])
          if @flashcard_set.save 
            render json: @flashcard_set, status: 200 
          else 
            render json: flashcard_sets.each do |flashcard |
              flashcard.error
            end  
          end 
        else 
          redirect_to devise_user_sign_in_path 
        end 
      end 

      def index 

        if user_signed_in? 
         
          if flashcard_sets = current_user.flashcard_sets.all
            render json: @flashcard_sets, status: 200
          else 
            render json: flashcard_sets.each do |flashcard |
                            flashcard.error
                          end 
          end
        else 
          render json: {}, status: 401
        end 

      end 

      def show 
      end 

      def edit 
      end 

      def update
      end 

      def delete 
      end 

      private 

      def flashcard_set_params
        binding.pry
        params.require(:flashcard_sets).permit(:title, :descripton)
      end

    end
  end
end

app/controllers/api/v1/flashcards_controller.rb
module Api 
  module V1
    class FlashcardsController < ApplicationController
      
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, only: [:app]
  
  def home
  end

  def app
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashcard_sets_helper.rb
module FlashcardSetsHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetterEnglishFlashcards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/app.html.erb
<div id="root"></div>
<%= javascript_pack_tag 'index' %>

app/views/welcome/home.html.erb
<nav style="text-align: right">
<% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>          
  <% else %>
    <%= link_to('Login', new_user_session_path)  %> |
    <%= link_to('Sign Up', new_user_registration_path)  %>  
  <% end %>
</nav>

<p>If you're logged in, check out <%= link_to "the app", app_path %>!</p>